In [1]:
import os
import re
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

### Persistindo o modelo de Machine Learning para o disco. ###

In [2]:
import joblib

#### Listando os arquivos em disco.

In [3]:
caminho_pickle = "/home/felipe/Projeto/Loan_Approval/Arquivos_pickle/model3_hiperparameters.pkl"

In [4]:
caminho_pickle 

'/home/felipe/Projeto/Loan_Approval/Arquivos_pickle/model3_hiperparameters.pkl'

#### Carregando o modelo a partir do disco para a memória.

In [5]:
# Carregar o modelo a partir do arquivo pickle usando joblib
modelo = joblib.load(caminho_pickle)

#print("Atributos do Modelo:\n\nClasses:{}\nEstimator:{}".format(modelo.classes_,modelo.estimator))

# Exibir os atributos do modelo
#print("Atributos do Modelo:\n")
#print(f"Number of estimators: {modelo.n_estimators}")
#print(f"Max depth: {modelo.max_depth}")
#print(f"Min samples split: {modelo.min_samples_split}")
#print(f"Min samples leaf: {modelo.min_samples_leaf}")
#print(f"Classes: {modelo.classes_}")


In [6]:
# Verificar os passos do pipeline, caso tenha usado pipeline
print("Steps do Pipeline:\n", modelo.named_steps)

# Acessar o estimador final no pipeline
modelo_final = modelo.named_steps['classifier']

# Visualizar os atributos do estimador final
print("Atributos do Modelo Final:\n\nClasses:{}\nEstimator:{}".format(modelo_final.classes_, modelo_final))



Steps do Pipeline:
 {'preprocessor': ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median'))]),
                                 Index(['Age', 'Married/Single', 'Experience', 'Profession', 'CURRENT_JOB_YRS',
       'House_Ownership', 'Car_Ownership', 'CURRENT_HOUSE_YRS', 'income'],
      dtype='object'))]), 'classifier': RandomForestClassifier(max_depth=32, n_estimators=11, random_state=42)}
Atributos do Modelo Final:

Classes:[0 1]
Estimator:RandomForestClassifier(max_depth=32, n_estimators=11, random_state=42)


In [8]:
# Suponha que o seu DataFrame tenha essas colunas (sem a coluna alvo)
df = pd.DataFrame({
    'Age': [25, 35, 45, 55, 65],
    'Married/Single': [1, 1, 0, 0 , 1],
    'Experience': [1, 10, 20, 30, 40],
    'Profession': [10, 16, 36, 44, 9],
    'CURRENT_JOB_YRS': [1, 5, 10, 15, 20],
    'House_Ownership': [0,1,1,2,2],
    'Car_Ownership': [0,1,1,0,1],
    'CURRENT_HOUSE_YRS': [1, 2, 3, 4, 5],
    'income': [30000, 50000, 70000, 90000, 110000]})

In [9]:
df

Age  Married/Single  Experience  Profession  CURRENT_JOB_YRS  \
0   25               1           1          10                1   
1   35               1          10          16                5   
2   45               0          20          36               10   
3   55               0          30          44               15   
4   65               1          40           9               20   

   House_Ownership  Car_Ownership  CURRENT_HOUSE_YRS  income  
0                0              0                  1   30000  
1                1              1                  2   50000  
2                1              1                  3   70000  
3                2              0                  4   90000  
4                2              1                  5  110000

In [10]:
# Fazer previsões
previsoes = modelo.predict(df)
previsoes

array([0, 0, 0, 0, 0])

In [11]:
modelo.predict_proba(df)

array([[0.54545455, 0.45454545],
       [0.72727273, 0.27272727],
       [0.57024793, 0.42975207],
       [0.68831169, 0.31168831],
       [0.54545455, 0.45454545]])

In [20]:
df.head(2)

Age  Experience  CURRENT_JOB_YRS  CURRENT_HOUSE_YRS  income  \
0   25           1                1                  1   30000   
1   35          10                5                  2   50000   

   Married/Single  Profession  House_Ownership  Car_Ownership  
0               1           2                1              0  
1               0           1                0              1

**Verificando o Dataset final gerado.**

In [39]:
teste = np.array([[30,8,3,3,5000,0,22,1,1]])

**Teste de Classificação.**

In [40]:
modelo.predict(teste)

array([0])

**Probabilidades de Classes.**

In [41]:
modelo.predict_proba(teste)

array([[0.60822511, 0.39177489]])