In [1]:
import os
import re
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

### Persistindo o modelo de Machine Learning para o disco. ###

In [2]:
import joblib

#### Listando os arquivos em disco.

In [8]:
caminho_pickle = "/home/felipe/Projeto/Loan_Approval/Arquivos_pickle/modelo_sem_scaler.pkl"

In [9]:
caminho_pickle 

'/home/felipe/Projeto/Loan_Approval/Arquivos_pickle/modelo_sem_scaler.pkl'

#### Carregando o modelo a partir do disco para a memória.

In [12]:
# Carregar o modelo a partir do arquivo pickle usando joblib
modelo = joblib.load(caminho_pickle)

#print("Atributos do Modelo:\n\nClasses:{}\nEstimator:{}".format(modelo.classes_,modelo.estimator))

# Exibir os atributos do modelo
print("Atributos do Modelo:\n")
print(f"Number of estimators: {modelo.n_estimators}")
print(f"Max depth: {modelo.max_depth}")
print(f"Min samples split: {modelo.min_samples_split}")
print(f"Min samples leaf: {modelo.min_samples_leaf}")
print(f"Classes: {modelo.classes_}")


Atributos do Modelo:

Number of estimators: 22
Max depth: 27
Min samples split: 5
Min samples leaf: 1
Classes: [0 1]


In [13]:
# Verificar os passos do pipeline, caso tenha usado pipeline
#print("Steps do Pipeline:\n", modelo.named_steps)

# Acessar o estimador final no pipeline
#modelo_final = modelo.named_steps['classifier']

# Visualizar os atributos do estimador final
#print("Atributos do Modelo Final:\n\nClasses:{}\nEstimator:{}".format(modelo_final.classes_, modelo_final))



In [35]:
# Suponha que o seu DataFrame tenha essas colunas (sem a coluna alvo)
df = pd.DataFrame({
    'Age': [25, 35, 45, 55, 65],
    'Experience': [1, 10, 20, 30, 40],
    'CURRENT_JOB_YRS': [1, 5, 10, 15, 20],
    'CURRENT_HOUSE_YRS': [1, 2, 3, 4, 5],
    'income': [30000, 50000, 70000, 90000, 110000],
    'Married/Single': [1, 1, 0, 0 , 1],
    'Profession': [10, 16, 36, 44, 9],
    'House_Ownership': [0,1,1,2,2],
    'Car_Ownership': [0,1,1,0,1]
})

In [36]:
df

Age  Experience  CURRENT_JOB_YRS  CURRENT_HOUSE_YRS  income  \
0   25           1                1                  1   30000   
1   35          10                5                  2   50000   
2   45          20               10                  3   70000   
3   55          30               15                  4   90000   
4   65          40               20                  5  110000   

   Married/Single  Profession  House_Ownership  Car_Ownership  
0               1          10                0              0  
1               1          16                1              1  
2               0          36                1              1  
3               0          44                2              0  
4               1           9                2              1

In [37]:
# Fazer previsões
previsoes = modelo.predict(df)
previsoes

array([0, 1, 1, 0, 0])

In [38]:
modelo.predict_proba(df)

array([[0.63149351, 0.36850649],
       [0.49742965, 0.50257035],
       [0.43426749, 0.56573251],
       [0.56529582, 0.43470418],
       [0.60300372, 0.39699628]])

In [20]:
df.head(2)

Age  Experience  CURRENT_JOB_YRS  CURRENT_HOUSE_YRS  income  \
0   25           1                1                  1   30000   
1   35          10                5                  2   50000   

   Married/Single  Profession  House_Ownership  Car_Ownership  
0               1           2                1              0  
1               0           1                0              1

**Verificando o Dataset final gerado.**

In [39]:
teste = np.array([[30,8,3,3,5000,0,22,1,1]])

**Teste de Classificação.**

In [40]:
modelo.predict(teste)

array([0])

**Probabilidades de Classes.**

In [41]:
modelo.predict_proba(teste)

array([[0.60822511, 0.39177489]])